"""
AI News Summarizer - AI 摘要生成模块

使用 OpenAI GPT 生成专业的公众号文章
"""

import os
import re
import logging
from datetime import datetime
from typing import List, Optional
from pathlib import Path

from src.config import load_config, get_openai_config, get_openrouter_config
from src.fetcher import NewsItem

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%H:%M:%S'
)
logger = logging.getLogger(__name__)


class Summarizer:
    """AI 摘要生成器"""
    
    def __init__(self):
        config = load_config()
        openai_config = get_openai_config(config)
        openrouter_config = get_openrouter_config(config)
        
        # 优先使用OpenRouter配置
        if openrouter_config.get("api_key"):
            self.api_key = openrouter_config.get("api_key")
            self.model = openrouter_config.get("model", "google/gemini-2.0-flash-001")
            self.base_url = openrouter_config.get("base_url", "https://openrouter.ai/api/v1")
        else:
            self.api_key = openai_config.get("api_key", "")
            if not self.api_key or self.api_key == "your_openai_api_key_here":
                self.api_key = os.environ.get("OPENAI_API_KEY", "")
            self.model = openai_config.get("model", "gpt-4o-mini")
            self.base_url = openai_config.get("base_url", None)
        
        if not self.api_key:
            logger.warning("OpenAI/OpenRouter API key not configured. Using mock summarization.")
            self.client = None
        else:
            try:
                from openai import OpenAI
                # 设置超时和重试参数
                kwargs = {
                    "api_key": self.api_key,
                    "timeout": 30.0,  # 30秒超时
                    "max_retries": 1  # 最多重试1次
                }
                if self.base_url:
                    kwargs["base_url"] = self.base_url
                
                self.client = OpenAI(**kwargs)
                logger.info(f"OpenAI client initialized ({self.model}, base_url={self.base_url})")
            except ImportError:
                logger.warning("openai library not installed")
                self.client = None
    
    def summarize_news(self, news_items: List[NewsItem]) -> str:
        """生成公众号文章"""
        if not self.client or not news_items:
            return self._mock_summarize(news_items)
        
        news_content = self._prepare_news_content(news_items)
        
        system_prompt = """你是一位资深 AI 领域深度观察者，擅长从新闻素材中提炼独特视角，写出有观点、有深度的原创评论。
写作要求：每篇独立构思，杜绝模板化套路；标题不落俗套，有钩子但不过度夸张；避免反复使用固定句式和结构。
对每条素材做事实性转述，不编造数据、不虚构人物，所有论断都必须来自给定素材。"""

        user_prompt = f"""请基于以下 AI 新闻素材，为微信公众号撰写一篇深度原创文章。

写作要求：
1. 从多条素材中提炼一个有价值的核心观点或主题，围绕它展开（而非逐条罗列成日报）
2. 标题要有辨识度，能引发思考，不使用"XX日报""今日速递"类模板词，不用 emoji 堆砌
3. 结构自然流畅，可以有小标题分区，但不要固定分类；允许"引申/反问/对比"等评论性段落
4. 每条重要事实后标注来源（Markdown 格式 [来源](链接)），确保可溯源
5. 结尾有一段作者视角的总结，发出值得读者思考的问题，输出观点而非情绪
6. 语言专业但有温度，去 AI 味

今日 AI 新闻素材：

{news_content}

请直接输出公众号文章内容（Markdown 格式），不要添加额外说明。"""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.9,
                max_tokens=4000,
                timeout=60
            )
            
            article = response.choices[0].message.content
            if article:
                logger.info(f"Article generated by {self.model}")
                return article
            return self._mock_summarize(news_items)
            
        except Exception as e:
            logger.error(f"Error calling OpenAI API: {e}")
            return self._mock_summarize(news_items)
    
    def _prepare_news_content(self, news_items: List[NewsItem]) -> str:
        """准备新闻素材文本"""
        content_parts = []
        
        for i, item in enumerate(news_items, 1):
            source_info = f"[{item.source}]" if item.source else ""
            content_parts.append(f"""
{i}. {source_info}{item.title}
   摘要：{item.description or "暂无摘要"}
   链接：{item.url}
""")
        
        return "\n".join(content_parts)
    
    def _mock_summarize(self, news_items: List[NewsItem]) -> str:
        """模拟摘要（无 API 时使用）"""
        today = datetime.now().strftime("%Y年%m月%d日")
        
        categories = self._categorize_news(news_items)
        
        article_parts = [
            f"# 🎯 {today} AI 资讯日报",
            "",
            f"各位读者朋友们，大家好！今天是{today}，让我们一起来看看 AI 领域又有哪些最新动态。",
            "",
            "---",
            ""
        ]
        
        for category, items in categories.items():
            emoji = self._get_category_emoji(category)
            article_parts.append(f"## {emoji} {category}")
            article_parts.append("")
            
            for item in items:
                article_parts.append(f"**{item.title}**")
                if item.description:
                    article_parts.append(f">{item.description}")
                if item.url:
                    article_parts.append(f"[原文链接]({item.url})")
                article_parts.append("")
        
        article_parts.extend([
            "---",
            "",
            "## 💡 今日点评",
            "",
            "AI 领域正在经历快速发展期，各大科技公司纷纷加码布局。" +
            "从今天的资讯来看，大模型能力和应用场景都在持续扩展。" +
            "建议读者朋友们持续关注这一领域的最新发展。",
            "",
            "---",
            "",
            f"📢 *本文由 AI 自动整理汇总，发布于{today}*"
        ])
        
        logger.info("Mock summary generated")
        return "\n".join(article_parts)
    
    def _categorize_news(self, news_items: List[NewsItem]) -> dict:
        """简单分类"""
        categories = {}
        
        for item in news_items:
            source = item.source.lower() if item.source else ""
            
            if any(kw in source for kw in ["openai"]):
                cat = "OpenAI 动态"
            elif any(kw in source for kw in ["google", "deepmind"]):
                cat = "Google DeepMind 动态"
            elif any(kw in source for kw in ["microsoft"]):
                cat = "Microsoft 动态"
            elif any(kw in source for kw in ["anthropic"]):
                cat = "Anthropic 动态"
            elif any(kw in source for kw in ["meta"]):
                cat = "Meta 动态"
            else:
                cat = "行业资讯"
            
            if cat not in categories:
                categories[cat] = []
            categories[cat].append(item)
        
        return categories
    
    def _get_category_emoji(self, category: str) -> str:
        """获取分类 emoji"""
        emojis = {
            "OpenAI 动态": "🟢",
            "Google DeepMind 动态": "🔵",
            "Microsoft 动态": "💻",
            "Anthropic 动态": "🤖",
            "Meta 动态": "📘",
            "行业资讯": "📰",
        }
        return emojis.get(category, "📌")


def generate_article(news_items: List[NewsItem], save_to_file: bool = True) -> str:
    """生成文章的便捷函数"""
    summarizer = Summarizer()
    article = summarizer.summarize_news(news_items)
    
    if save_to_file:
        output_dir = Path("output")
        output_dir.mkdir(exist_ok=True)
        
        today = datetime.now().strftime("%Y%m%d")
        md_filename = output_dir / f"article_{today}.md"
        
        with open(md_filename, "w", encoding="utf-8") as f:
            f.write(article)
        
        logger.info(f"Article saved: {md_filename}")
    
    return article


if __name__ == "__main__":
    from src.fetcher import fetch_news, get_mock_news
    
    print("Testing summarizer with mock data...")
    mock_news = get_mock_news(5)
    
    article = generate_article(mock_news)
    print("\n" + "="*50)
    print(article[:2000])
